#server:
#  port: 8081
#  address: 127.0.0.1
#  address: 192.168.1.64
server:
  port: 80
  address: 0.0.0.0

spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

#spring:
#  data:
#    mongodb:
#      database: itg
#      port: 27017
#      host: localhost

services:
  telegram-bot-service: ${TELEGRAM_BOT_SERVICE}
  vpbx-service: ${VPBX_SERVICE}